config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions' }
  resources :posts do 
    collection do 
      post :create_comment
      delete :destroy_comment
      post :like_dislike
      delete :like_dislike
      post :like_post
    end
  end


  root "homes#index"
  get 'homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments , dependent: :destroy
  has_many :photos ,dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @post = Post.all
  end

  def show
  
   @post = Post.find(params[:id])
   @comments = @post.comments
   @photo = @post.photos.paginate(page: params[:page], per_page: 1)

  end

  def edit
    @post = Post.new
  end

  def update
     #byebug
     @post = Post.find(params[:id])
     @post.update(caption: params[:post][:caption])
     redirect_to root_path
  end

  def new
    @post = Post.new
  end

  def create
    #byebug
    @post = current_user.posts.new(caption: params[:post][:caption])
     @post.save
     params[:post][:avatar].each do |photo|
           @photu = @post.photos.create(avatar: photo)
         end
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end
  def create_comment
    #byebug
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(feedback: params[:feedback], user_id: current_user.id)
    @comment.save
    @comments = @post.comments

  end
  
  def destroy_comment
    # byebug
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    @comments = @post.comments
  end

  def like_dislike
     @comment = Comment.find(params[:comment_id])
     if params[:like] == "true"
         @like = @comment.likes.new(user_id: current_user.id)
         @like.save
     else
         @comment.likes.find_by(user_id:current_user.id).destroy
     end
  end

  def like_post
    byebug
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<table>
 		<tr>
 			<th>Feedback</th>
 		</tr>
 		<% @comments.reverse.each do |comment| %>
 		<tr>
 			<td>
 				<%= comment.feedback %><br><strong><em> ~ by <%= comment.user.email %></em></strong>
 			</td>
 			<% if comment.user == current_user || current_user.role?.eql?("Admin") %>
 			<td><%= button_to "DELETE" ,destroy_comment_posts_path(post_id: @post.id , comment_id: comment.id),method: :delete ,remote: true %></td>
 			<% end %>
 			<td>
	 			<div id = "like_<%= comment.id %>" >
					<%= render "like", comment: comment  %>
				</div>	
 			</td>
 		     
 		</tr>
 		
 		<% end %>
 	</table>

app/views/posts/_like.html.erb
 <% if comment.likes.map(&:user_id).include?(current_user.id) %>
 <%= button_to "Dislike" ,like_dislike_posts_path(comment_id: comment.id ,like: false ), method: :delete , remote: true %> 
 <% else %>
    <%= button_to "Like" , like_dislike_posts_path(comment_id: comment.id ,like: true ), method: :post , remote: true %>
 <% end %>
 <%= comment.likes.count %>Likes

app/views/posts/_post.html.erb
<table>
	<tr>
		<th>Caption</th>
	</tr>
	<% @posts.each do |post| %>
    <tr>
    	<td><em><%= post.user.email %><em></td>
    	<td><%= post.caption%></td>
    	<% if post.user == current_user || current_user.role? == "Admin" %>
    	
    	<td><%= button_to  "EDIT", edit_post_path(post),method: :get%></td>
    	<td><%= button_to  "DELETE", post_path(post),method: :delete%></td>
    	

    	<% end %><td><%= button_to  "SHOW", post_path(post),method: :get%></td>
    </tr>

	<% end %>

app/views/posts/create_comment.js.erb
$("#comment_lists").html("<%= escape_javascript(render partial: 'comment'  ) %>");

app/views/posts/destroy_comment.js.erb
$("#comment_lists").html("<%= escape_javascript(render partial: 'comment'  ) %>");

app/views/posts/edit.html.erb
<h1>Edit Post </h1>
<%= form_with model: @post, url: post_path, method: :put do |form| %>
<div><strong>
	<%= form.label :caption %> ~<br> </strong>
	<%= form.text_field :caption %>
</div>
<div class="field">
    <%= form.file_field :avatar ,multiple: true %>
  </div>
<div>
	<%= form.submit "Update" %>
</div>
<% end %>
<%= link_to "Back" , root_path %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/like_dislike.js.erb
$("#like_" + <%= @comment.id %>).html("<%= escape_javascript(render partial: 'like' , locals: { comment: @comment }  ) %>");

app/views/posts/new.html.erb
<h1>NEW Posts</h1>
<%= form_with model: @post, url: posts_path, method: :post do |form| %>
<div><strong>
	<%= form.label :caption %> ~<br> </strong>
	<%= form.text_field :caption %>
</div>
 <div class="field">
    <%= form.file_field :avatar ,multiple: true %>
  </div>
 
<div>
	<%= form.submit "Save" %>
</div>
<% end %>
<%= link_to "Back" , root_path %>

app/views/posts/show.html.erb
<h1>Show Posts</h1>
<div>
	<% unless  @photo.nil? %>
		<% @photo.each do |photo| %>
			<%= image_tag photo.avatar.url %>
		<% end %>
	<% end %>
	<%= will_paginate @photo %>
</div>

<div>
	<strong>Email</strong>
	<%= @post.user.email %>
	</div>
	<br>
<div>
	<strong>Caption</strong>
	<%= @post.caption %>
    <!-- loop for multiple photo -->
	<% @photo.each do |photo| %>
	<%#= image_tag photo.avatar.url %>
	<% end %>
	<%= link_to "Back" , root_path%>
	</div>
    <!--  create comment -->
	<%= form_with model: @comment ,url:  create_comment_posts_path, method: :post , remote: true do |form| %>

	<div>
		<%= form.label :feedback %>
		<%= form.text_field :feedback%>
	</div>
	<%= form.hidden_field :post_id, value: @post.id %>
	<div>
		<%= form.submit "create comment" %>

 	</div>
 	<% end %>
	<h2>Comments</h2>
 	<div id = "comment_lists">
 		<%= render "comment" %>
 	</div>
 
	<%= link_to "Back", root_path%>

app/views/posts/user:references.html.erb
<h1>Posts#user:references</h1>
<p>Find me in app/views/posts/user:references.html.erb</p>